my_TRR:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Velocity Controllers ---------------------------------------
  joint1_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: right_active_wheel_joint
    pid: 
      p: 5
      i: 20
      i_clamp: 100

  joint2_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: left_active_wheel_joint
    pid: 
      p: 5
      i: 20
      i_clamp: 100

  joint3_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: right_shooting_wheel_joint
    pid: 
      p: 0.1
      i: 0.4
      i_clamp: 100

  joint4_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: left_shooting_wheel_joint
    pid: 
      p: 0.1
      i: 0.4
      i_clamp: 100

